package io.titan.graphql.management;

import io.titan.graphql.TitanGraphqlProjection;
import io.titan.graphql.TitanGraphqlProjectionModel;

public final class TitanGraphqlManagementProjection {

    private TitanGraphqlManagementProjection() {
    }

    public static TitanGraphqlProjectionModel projectionModel() {
        return TitanGraphqlProjection.model()
                .relayConnectionRoot("workspaces", "ManagedWorkspace")
                .pageSize(25, 100)
                .addRoot()
                .pointRoot("workspace", "ManagedWorkspace", "id")
                .pointRoot("model", "ManagedGraphqlModel", "id")
                .pointRoot("modelDraft", "ModelDraft", "id")
                .pointRoot("validationReport", "ValidationReport", "id")
                .pointRoot("artifactSet", "ArtifactSet", "id")
                .pointRoot("driftReport", "DriftReport", "id")
                .pointRoot("deployment", "Deployment", "id")
                .pointRoot("previewBuild", "PreviewBuild", "id")
                .relayConnectionRoot("observedOperations", "ObservedOperation")
                .pageSize(25, 100)
                .addRoot()
                .pointRoot("observedOperation", "ObservedOperation", "id")
                .pointRoot("operationRegistry", "OperationRegistry", "id")
                .pointRoot("usageReport", "UsageReport", "id")
                .type("ManagedWorkspace")
                .table("titan_graphql_management", "managed_workspaces", "managed_workspaces", "id")
                .scalarField("id", "id")
                .scalarField("name", "name")
                .scalarField("description", "description")
                .scalarField("defaultEnvironment", "default_environment")
                .scalarField("createdAt", "created_at")
                .scalarField("updatedAt", "updated_at")
                .addType()
                .type("ManagedGraphqlModel")
                .table("titan_graphql_management", "managed_models", "managed_models", "id")
                .scalarField("id", "id")
                .scalarField("workspaceId", "workspace_id")
                .scalarField("name", "name")
                .scalarField("displayName", "display_name")
                .scalarField("description", "description")
                .scalarField("currentDraftId", "current_draft_id")
                .scalarField("activeDeploymentId", "active_deployment_id")
                .scalarField("latestValidationReportId", "latest_validation_report_id")
                .scalarField("latestArtifactSetId", "latest_artifact_set_id")
                .scalarField("createdAt", "created_at")
                .scalarField("updatedAt", "updated_at")
                .addType()
                .type("ModelDraft")
                .table("titan_graphql_management", "model_drafts", "model_drafts", "id")
                .scalarField("id", "id")
                .scalarField("modelId", "model_id")
                .scalarField("status", "status")
                .scalarField("sourceFormat", "source_format")
                .scalarField("semanticHash", "semantic_hash")
                .scalarField("validationReportId", "validation_report_id")
                .scalarField("artifactSetId", "artifact_set_id")
                .scalarField("driftReportId", "drift_report_id")
                .scalarField("createdBy", "created_by")
                .scalarField("createdAt", "created_at")
                .scalarField("updatedAt", "updated_at")
                .addType()
                .type("ValidationReport")
                .table("titan_graphql_management", "validation_reports", "validation_reports", "id")
                .scalarField("id", "id")
                .scalarField("draftId", "draft_id")
                .scalarField("status", "status")
                .scalarField("summary", "summary")
                .scalarField("errors", "errors")
                .scalarField("warnings", "warnings")
                .scalarField("infos", "infos")
                .scalarField("createdAt", "created_at")
                .addType()
                .type("ArtifactSet")
                .table("titan_graphql_management", "artifact_sets", "artifact_sets", "id")
                .scalarField("id", "id")
                .scalarField("draftId", "draft_id")
                .scalarField("semanticHash", "semantic_hash")
                .scalarField("sdlHash", "sdl_hash")
                .scalarField("introspectionHash", "introspection_hash")
                .scalarField("conformanceHash", "conformance_hash")
                .scalarField("generatedSqlHash", "generated_sql_hash")
                .scalarField("generationProfile", "generation_profile")
                .scalarField("createdAt", "created_at")
                .addType()
                .type("DriftReport")
                .table("titan_graphql_management", "drift_reports", "drift_reports", "id")
                .scalarField("id", "id")
                .scalarField("draftId", "draft_id")
                .scalarField("status", "status")
                .scalarField("checkedAgainst", "checked_against")
                .scalarField("summary", "summary")
                .scalarField("issueCount", "issue_count")
                .scalarField("createdAt", "created_at")
                .addType()
                .type("Deployment")
                .table("titan_graphql_management", "deployments", "deployments", "id")
                .scalarField("id", "id")
                .scalarField("modelId", "model_id")
                .scalarField("draftId", "draft_id")
                .scalarField("artifactSetId", "artifact_set_id")
                .scalarField("environment", "environment")
                .scalarField("status", "status")
                .scalarField("deployedBy", "deployed_by")
                .scalarField("deployedAt", "deployed_at")
                .scalarField("rollbackTargetDeploymentId", "rollback_target_deployment_id")
                .scalarField("runtimeHealthId", "runtime_health_id")
                .addType()
                .type("PreviewBuild")
                .table("titan_graphql_management", "preview_builds", "preview_builds", "id")
                .scalarField("id", "id")
                .scalarField("modelId", "model_id")
                .scalarField("draftId", "draft_id")
                .scalarField("artifactSetId", "artifact_set_id")
                .scalarField("environment", "environment")
                .scalarField("status", "status")
                .scalarField("previewEndpoint", "preview_endpoint")
                .scalarField("previewConsoleUrl", "preview_console_url")
                .scalarField("schemaHash", "schema_hash")
                .scalarField("artifactManifestPath", "artifact_manifest_path")
                .scalarField("artifactManifestHash", "artifact_manifest_hash")
                .scalarField("operationRegistryId", "operation_registry_id")
                .scalarField("expiresAt", "expires_at")
                .scalarField("createdBy", "created_by")
                .scalarField("createdAt", "created_at")
                .addType()
                .type("ObservedOperation")
                .table("titan_graphql_management", "observed_operations", "observed_operations", "id")
                .scalarField("id", "id")
                .scalarField("modelId", "model_id")
                .scalarField("environment", "environment")
                .scalarField("role", "role")
                .scalarField("client", "client")
                .scalarField("operationHash", "operation_hash")
                .scalarField("operationName", "operation_name")
                .scalarField("document", "document")
                .scalarField("status", "status")
                .scalarField("depth", "depth")
                .scalarField("estimatedCost", "estimated_cost")
                .scalarField("fieldUsage", "field_usage")
                .scalarField("firstSeenAt", "first_seen_at")
                .scalarField("lastSeenAt", "last_seen_at")
                .scalarField("observedCount", "observed_count")
                .addType()
                .type("OperationRegistry")
                .table("titan_graphql_management", "operation_registries", "operation_registries", "id")
                .scalarField("id", "id")
                .scalarField("modelId", "model_id")
                .scalarField("environment", "environment")
                .scalarField("mode", "mode")
                .scalarField("updatedAt", "updated_at")
                .addType()
                .type("UsageReport")
                .table("titan_graphql_management", "usage_reports", "usage_reports", "id")
                .scalarField("id", "id")
                .scalarField("modelId", "model_id")
                .scalarField("environment", "environment")
                .scalarField("version", "version")
                .scalarField("window", "window")
                .scalarField("summary", "summary")
                .scalarField("totalOperations", "total_operations")
                .scalarField("totalRequests", "total_requests")
                .scalarField("operations", "operations")
                .scalarField("fields", "fields")
                .scalarField("roles", "roles")
                .scalarField("clients", "clients")
                .scalarField("environments", "environments")
                .scalarField("versions", "versions")
                .scalarField("deprecatedFieldsInUse", "deprecated_fields_in_use")
                .scalarField("unusedFields", "unused_fields")
                .scalarField("policyRejections", "policy_rejections")
                .scalarField("slowOperations", "slow_operations")
                .scalarField("generatedAt", "generated_at")
                .addType()
                .build();
    }
}
