FROM eclipse-temurin:21-jdk AS unpack

COPY *-control-job-worker.zip /tmp/worker.zip
RUN mkdir -p /opt/titan && cd /opt/titan && jar xf /tmp/worker.zip && chmod +x bin/titan-graphql-control-worker bin/titan-graphql-control

FROM eclipse-temurin:21-jre

COPY --from=unpack --chown=10001:10001 /opt/titan /opt/titan
USER 10001:10001
WORKDIR /opt/titan
ENTRYPOINT ["/opt/titan/bin/titan-graphql-control-worker"]
