FROM eclipse-temurin:21-jdk AS unpack

COPY *-database-http-frontend.zip /tmp/frontend.zip
RUN mkdir -p /opt/titan && cd /opt/titan && jar xf /tmp/frontend.zip && chmod +x bin/titan-graphql-database-http

FROM eclipse-temurin:21-jre

COPY --from=unpack --chown=10001:10001 /opt/titan /opt/titan
USER 10001:10001
WORKDIR /opt/titan
EXPOSE 8080
ENTRYPOINT ["/opt/titan/bin/titan-graphql-database-http"]
